### ISSUE TITLE
No FTP support

### ISSUE THREAD

**Issue by NotAlkaline** [paulmaunders/TFTP-PXE-Boot-Server#1]
Hi,
 what a great tool here, but I don't see any possible FTP use of this fpr my PXE, can you point me out this function (if available). It really fasten the transfers :)

I have a Synology DSM 5

**Comment by paulmaunders** [comment]
The initial bootloader menu (PXELINUX.0) is loaded from TFTP, but you may be able to change the DHCP options to point an FTP or HTTP location instead. 

It is also possible to specify new HTTP or FTP locations for the kernel, initrd and kickstart files by modifying the [pxelinux.cfg/default](https://github.com/paulmaunders/TFTP-PXE-Boot-Server/blob/master/pxelinux.cfg/default) file.

I haven't tried it myself, but there's some further info here: http://www.syslinux.org/wiki/index.php/PXELINUX

> Since version 5.10, a special PXELINUX binary, lpxelinux.0, natively supports HTTP and FTP transfers, greatly increasing load speed and allowing for standard HTTP scripts to present PXELINUX's configuration file. To use HTTP or FTP, use standard URL syntax as filename; use DHCP options to transmit a suitable URL prefix to the client, or use the "pxelinux-options" tool provided in the "utils" directory to program it directly into the lpxelinux.0 file.

Let me know if you have any success, and if you do, perhaps you could contribute some instructions for this project's README.
